[package]
name = "aoc_utils"
version = "0.1.0"
authors = ["J. Fernando SÃ¡nchez <balkian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
clap = "2.33.3"
